export type IWorkdayEmployee = {
    guid: string,
    email: string,
    firstName: string,
    lastName: string,
    preferredFirsName: string,
    preferredLastName: string,
    segment: string,
    companyHierarchy: string;
    costCenterLevel1: string,
    costCenterLevel2: string,
    costCenterLevel3: string,
    costCenterLevel4: string,
    businessTitle: string,
    employeeId: string,
    employeeType: string,
    jobProfile: string,
    jobLevel: string,
    jobFamily: string,
    jobFamilyGroup: string,
    costCenter: string,
    managementLevel: string,
    timeType: string,
    location: string,
    timeInGrade: string,
    globalLOS: string,
    hireDate: Date,
    locationDescription: string,
    countryCode: string,
    ppid: string,
    partyId: string,
    globalCompetencyNetworkDescription: string,
    supervisoryOrganization: string,
    employeeStatus: string
    workdayRelationshipLeader?: IWorkdayEmployee;
    workdayMatrixManager?: IWorkdayEmployee;
    workdayTalentConsultant?: IWorkdayEmployee;
}